apiVersion: split.smi-spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: target-ts
spec:
  service: target-svc
  matches:
  - kind: HTTPRouteGroup
    name: ab-test
  backends:
  - service: target-v2-1
    weight: 100
---
apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: ab-test
spec:
  matches:
  - name: beta-users
    headers:
    - user-id: "1"
